## Part A:Array Creation

In [1]:
import numpy as np
D1=np.arange(1,11)
print(D1)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
D2=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(D2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
d=np.linspace(0,1,5)
print(d)

[0.   0.25 0.5  0.75 1.  ]


In [4]:
print(np.eye(3,k=0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Part B:Array Operation

In [5]:
a=np.array([2,4,6]) 
b=np.array([1,3,5])
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Addition: [ 3  7 11]
Substraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]


In [6]:
arr=[1,2,3,4,5]
print(np.square(arr))

[ 1  4  9 16 25]


# Part C:Indexing and Slicing

In [7]:
 arr=np.array([10,20,30,40,50])

In [8]:
print(arr[:3])
print(arr[-2:])
print(arr[2])

[10 20 30]
[40 50]
30


In [9]:
arr2=np.array([[5,10,15],[20,25,30]])

In [10]:
print(arr2[1,2])
print(arr2[:,1])
print(arr2[0,:])

30
[10 25]
[ 5 10 15]


# Part D: Aggregate Functions

In [11]:
arr=np.array([10, 20, 30, 40, 50])

In [12]:
print(np.sum(arr))     
print(np.mean(arr))     
print(np.std(arr))     
print(np.min(arr))     
print(np.max(arr))  

150
30.0
14.142135623730951
10
50


# Part E: Boolean Masking and Random Numbers

In [13]:
array=np.array([5, 10, 15, 20, 25, 30])
print(array[array > 15])

[20 25 30]


In [14]:
print(np.random.randint(10,50,size=(2,3)))

[[23 23 17]
 [12 28 11]]
