# Part A:Array Creation

In [1]:
import numpy as np
D1=np.arange(1,11)
print(D1)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
D2=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(D2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
5.Create two array: a=[2,4,6] and b=[1,3,5] .Perform the following Addition Substraction Multiplication Divisionprint(d)

[0.   0.25 0.5  0.75 1.  ]


In [4]:
print(np.eye(3,k=0))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Part B:Array Operation